### ISSUE TITLE
This code on node 4.3.2

### ISSUE THREAD

**Issue by projetoarduino** [momodalo/broadlinkjs#3]
Hi i need run this code on node old version 4.3.2.

I convert same things example:

Buffer.alloc i change to new Buffer

let to var

But i need help to this

 var rm2 = dev as broadlink.RM2;
                         ^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

Do you know what this code would look like in an old version of the node

Congratulations on your work!

**Comment by momodalo** [comment]
Hi, have you do "let broadlink = require('broadlinkjs');" before that?

**Comment by momodalo** [comment]
If you want to generate a device directly without through discovering, I didn't export those api. You can try to modify the module and explore the genDevice function

**Comment by projetoarduino** [comment]
You dont know how i convert this part of code to work to old version node?

"as" is not implement in node 4.3.2

var rm2 = dev as broadlink.RM2;

**Comment by momodalo** [comment]
sorry, I don't know this.

**Comment by projetoarduino** [comment]
Can you please explain to me what this line does?

**Comment by aikeru** [comment]
Hi @projetoarduino , I'm not affiliated with the project, but I think I understand your issue.
It looks like you are referencing the test.ts file, which is TypeScript.
node.js doesn't understand TypeScript, it has to be compiled with the TypeScript compiler first.
Fortunately, there's a test.js file in the same folder, and you should probably use that instead. Node should understand it.

The "as" keyword in TypeScript gets compiled away at runtime. It is just a hint to the editor/IDE as to what the type of the object is going to be.
